# Generated by Django 4.1.6 on 2023-02-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField()),
                ("role_id", models.BigIntegerField(null=True)),
                ("channel_id", models.BigIntegerField(null=True)),
                ("message_id", models.BigIntegerField(null=True)),
                ("member_id", models.BigIntegerField()),
                (
                    "member_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "member_display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CHAIN", "чейн"),
                            ("ONCE", "разовый"),
                            ("AWAKENED", "пробужденный"),
                            ("TOI", "ТОИ"),
                            ("VEORA", "веора"),
                            ("SIEGE", "осада"),
                            ("CLUSTER", "кластер"),
                            ("CLAN", "клан"),
                            ("ALLIANCE", "альянс"),
                            ("UNKNOWN", "не известно"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("TIME", "за минут(а)"),
                            ("THING", "за штук(а)"),
                            ("VISIT", "за визит(ы)"),
                            ("UNKNOWN", "не известно"),
                        ],
                        max_length=32,
                    ),
                ),
                ("capacity", models.IntegerField(default=0)),
                ("cost", models.IntegerField(default=0)),
                ("penalty", models.IntegerField(default=50)),
                ("military", models.IntegerField(default=20)),
                ("overnight", models.IntegerField(default=25)),
                ("title", models.CharField(max_length=64)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "подготовка"),
                            ("STARTED", "запущено"),
                            ("FINISHED", "завершено"),
                            ("CANCELED", "остановлено"),
                            ("UNKNOWN", "не известно"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("is_military", models.BooleanField(default=False)),
                ("is_overnight", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EventChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField()),
                ("role_id", models.BigIntegerField(null=True)),
                ("channel_id", models.BigIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EventModerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField()),
                ("role_id", models.BigIntegerField(null=True)),
                ("channel_id", models.BigIntegerField(null=True)),
                ("member_id", models.BigIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EventTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CHAIN", "чейн"),
                            ("ONCE", "разовый"),
                            ("AWAKENED", "пробужденный"),
                            ("TOI", "ТОИ"),
                            ("VEORA", "веора"),
                            ("SIEGE", "осада"),
                            ("CLUSTER", "кластер"),
                            ("CLAN", "клан"),
                            ("ALLIANCE", "альянс"),
                            ("UNKNOWN", "не известно"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("TIME", "за минут(а)"),
                            ("THING", "за штук(а)"),
                            ("VISIT", "за визит(ы)"),
                            ("UNKNOWN", "не известно"),
                        ],
                        max_length=32,
                    ),
                ),
                ("capacity", models.IntegerField(default=0)),
                ("cost", models.IntegerField(default=0)),
                ("penalty", models.IntegerField(default=50)),
                ("military", models.IntegerField(default=20)),
                ("overnight", models.IntegerField(default=25)),
                ("quantity", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=64)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_id", models.BigIntegerField()),
                ("member_name", models.CharField(blank=True, max_length=255)),
                ("member_display_name", models.CharField(blank=True, max_length=255)),
                ("reward", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FULL", "присутствовал"),
                            ("PARTIAL", "опоздал"),
                            ("ABSENT", "отсутствовал"),
                            ("UNKNOWN", "не известно"),
                        ],
                        default="ABSENT",
                        max_length=32,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_attendances",
                        to="activity.event",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="eventattendance",
            constraint=models.UniqueConstraint(
                fields=("event", "member_id"), name="event-member-reacted"
            ),
        ),
    ]
