# Generated by Django 4.1.6 on 2023-02-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField(null=True)),
                ('channel_id', models.BigIntegerField(null=True)),
                ('message_id', models.BigIntegerField(unique=True)),
                ('author_id', models.BigIntegerField()),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_display_name', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('STARTED', 'Started'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='STARTED', max_length=32)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('event_type', models.CharField(choices=[('CHAIN', 'Chain'), ('ONCE', 'Once'), ('AWAKENED', 'Awakened'), ('TOI', 'Toi'), ('VEORA', 'Veora'), ('SIEGE', 'Siege'), ('INTERCLUSTER', 'Intercluster'), ('CLAN', 'Clan'), ('ALLY', 'Ally')], max_length=32)),
                ('cost', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('capacity_unit', models.CharField(choices=[('MINUTE', 'Minute'), ('THING', 'Thing'), ('VISIT', 'Visit')], max_length=32)),
                ('lateness_percent', models.IntegerField(default=80)),
                ('nightly_percent', models.IntegerField(default=25)),
                ('quantity', models.IntegerField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameEventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('event_type', models.CharField(choices=[('CHAIN', 'Chain'), ('ONCE', 'Once'), ('AWAKENED', 'Awakened'), ('TOI', 'Toi'), ('VEORA', 'Veora'), ('SIEGE', 'Siege'), ('INTERCLUSTER', 'Intercluster'), ('CLAN', 'Clan'), ('ALLY', 'Ally')], max_length=32)),
                ('cost', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('capacity_unit', models.CharField(choices=[('MINUTE', 'Minute'), ('THING', 'Thing'), ('VISIT', 'Visit')], max_length=32)),
                ('lateness_percent', models.IntegerField(default=80)),
                ('nightly_percent', models.IntegerField(default=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameEventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_display_name', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('FULL', 'Full'), ('LATE', 'Late'), ('NONE', 'None')], default='NONE', max_length=32)),
                ('reward', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='game_activity.gameevent')),
            ],
        ),
    ]
