# Generated by Django 4.1.6 on 2023-02-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='eventattendance',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='eventchannel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='eventmoderator',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='eventtemplate',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveConstraint(
            model_name='eventattendance',
            name='event-member-reacted',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'подготовка'), ('STARTED', 'запущено'), ('FINISHED', 'завершено'), ('CANCELED', 'остановлено')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('CHAIN', 'чейн'), ('ONCE', 'разовый'), ('AWAKENED', 'пробужденный'), ('TOI', 'ТОИ'), ('VEORA', 'веора'), ('SIEGE', 'осада'), ('CLUSTER', 'кластер'), ('CLAN', 'клан'), ('ALLIANCE', 'альянс')], max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.CharField(choices=[('TIME', 'за минут(а)'), ('THING', 'за штук(а)'), ('VISIT', 'за визит(ы)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='type',
            field=models.CharField(choices=[('FULL', 'присутствовал'), ('PARTIAL', 'опоздал'), ('ABSENT', 'отсутствовал')], default='ABSENT', max_length=32),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='type',
            field=models.CharField(choices=[('CHAIN', 'чейн'), ('ONCE', 'разовый'), ('AWAKENED', 'пробужденный'), ('TOI', 'ТОИ'), ('VEORA', 'веора'), ('SIEGE', 'осада'), ('CLUSTER', 'кластер'), ('CLAN', 'клан'), ('ALLIANCE', 'альянс')], max_length=32),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='unit',
            field=models.CharField(choices=[('TIME', 'за минут(а)'), ('THING', 'за штук(а)'), ('VISIT', 'за визит(ы)')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('event', 'member_id'), name='event-attendance-member'),
        ),
    ]
