# Generated by Django 5.0.1 on 2024-01-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "подготовка"),
                    ("STARTED", "запущено"),
                    ("FINISHED", "завершено"),
                    ("CANCELED", "остановлено"),
                    ("DELETED", "удалено"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
