# Generated by Django 4.1.6 on 2023-02-16 11:50

from django.db import migrations, models


def change_capacity_unit(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Event = apps.get_model('activity', 'Event')
    Event.objects.filter(unit='THING').update(unit='BOSS')

    EventTemplate = apps.get_model('activity', 'EventTemplate')
    EventTemplate.objects.filter(unit='THING').update(unit='BOSS')


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_event_options_alter_eventattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.CharField(choices=[('TIME', 'за минут(а)'), ('BOSS', 'за босса(ов)'), ('VISIT', 'за визит(ы)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='unit',
            field=models.CharField(choices=[('TIME', 'за минут(а)'), ('BOSS', 'за босса(ов)'), ('VISIT', 'за визит(ы)')], max_length=32),
        ),
        migrations.RunPython(change_capacity_unit),

    ]
