name: "Lint"

on:
  pull_request:
    branches:
      - "main"
      - "development"
  push:
    branches:
      - "*"
      - "**"

jobs:
  flake8:
    name: "flake8"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: "Set up Poetry"
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.7.1"
      - name: "Install flake8"
        run: poetry install --with dev
      - name: "Check"
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: flake8
          run: poetry run flake8 ./src/
  isort:
    name: "isort"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: "Set up Poetry"
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.7.1"
      - name: "Install isort"
        run: poetry install --with dev
      - name: "Check"
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: isort
          run: poetry run isort ./src/ --check --diff --profile black
  black:
    name: "black"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Check"
        uses: psf/black@stable
        with:
          options: --config pyproject.toml --check
          src: ./src/
  ruff:
    name: "ruff"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Check"
        uses: chartboost/ruff-action@v1
        with:
          src: ./src/
