name: "Release publish"

on:
  release:
    types: [released]

jobs:
  docker-publish:
    name: "Docker Publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
      - name: "Login to DockerHub Container Registry"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Tag Latest"
        run: |
          docker buildx imagetools create --tag whenessel/dkp-activity-system:latest whenessel/dkp-activity-system:${{ github.event.release.name }}
